---
title: "CodeBook2"
output: html_document
---

##Introduction:

The code follows the five given steps:

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement.
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

##Variables

features - contains data from the downloaded files.
activityType  - contains data from the downloaded files.
SubTrain  - contains data from the downloaded files.
X_Train  - contains data from the downloaded files.
Y_Train  - contains data from the downloaded files.
TrainData  - contains combined train data.

SubTest - contains data from the downloaded files.
X_Test - contains data from the downloaded files.
Y_Test - contains data from the downloaded files.
TestData - contains combined test data.
FinalData - contains all data
